apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javawebappcontainer
        image: 624570335512.dkr.ecr.ap-south-1.amazonaws.com/javaapp:${buildNumber}
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: java-web-app
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: java-web-app
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 40


---

apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  type: ClusterIP
  selector:
    app: javaapp
  ports:
  - port: 80
    targetPort: 8080
    
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: javaapphpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: javadeployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource  
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
