apiVersion: v1
kind: Pod
metadata:
  name: javapod
  labels:
    app: javaapp
spec:
  containers:
  - name: javawebappcontainer
    image: 015901552966.dkr.ecr.ap-south-1.amazonaws.com/java-web-app:1
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "250m"
        memory: "300Mi"
    ports:
    - containerPort: 8080
    
--- 

apiVersion: v1 
kind: Service
metadata:
  name: javaappsvc
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - port: 80
    targetPort: 8080
